import pandas
import numpy as np
dataframe = pandas.read_csv('adult randomized.csv')
a,trash = np.split(dataframe, [int(.1*len(dataframe))])
b,trash = np.split(dataframe, [int(.2*len(dataframe))])
c,trash = np.split(dataframe, [int(.3*len(dataframe))])
d,trash = np.split(dataframe, [int(.4*len(dataframe))])
e,trash = np.split(dataframe, [int(.5*len(dataframe))])
f,trash = np.split(dataframe, [int(.6*len(dataframe))])
g,trash = np.split(dataframe, [int(.7*len(dataframe))])
h,test = np.split(dataframe, [int(.8*len(dataframe))])
a.to_csv('tenPercent.csv')
b.to_csv('twentyPercent.csv')
c.to_csv('thirtyPercent.csv')
d.to_csv('fourtyPercent.csv')
e.to_csv('fiftyPercent.csv')
f.to_csv('sixtyPercent.csv')
g.to_csv('seventyPercent.csv')
h.to_csv('eightyPercent.csv')
test.to_csv('testSet.csv')
print(f)