import pandas
import numpy as np
dataframe = pandas.read_csv('RandomTit.csv')
a,trash = np.split(dataframe, [int(.1*len(dataframe))])
b,trash = np.split(dataframe, [int(.2*len(dataframe))])
c,trash = np.split(dataframe, [int(.3*len(dataframe))])
d,trash = np.split(dataframe, [int(.4*len(dataframe))])
e,trash = np.split(dataframe, [int(.5*len(dataframe))])
f,trash = np.split(dataframe, [int(.6*len(dataframe))])
g,trash = np.split(dataframe, [int(.7*len(dataframe))])
h,test = np.split(dataframe, [int(.8*len(dataframe))])
a.to_csv('10Tit.csv')
b.to_csv('20Tit.csv')
c.to_csv('30Tit.csv')
d.to_csv('40Tit.csv')
e.to_csv('50Tit.csv')
f.to_csv('60Tit.csv')
g.to_csv('70Tit.csv')
h.to_csv('80Tit.csv')
test.to_csv('testTit.csv')
print(f)